name: Modify Device Tree for TWRP

on:
  push:
    branches:
      - main

jobs:
  modify_device_tree:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y git curl

      - name: Clone LineageOS Device Tree for OnePlus Nord CE 3 Lite 5G (larry)
        run: |
          # Clone the LineageOS device tree for OnePlus Nord CE 3 Lite 5G (larry)
          git clone https://github.com/LineageOS/android_device_oneplus_larry.git device_tree_twrp_oneplus_larry

      - name: Modify the Device Tree for TWRP
        run: |
          cd device_tree_twrp_oneplus_larry

          # Remove boot-specific files like init.rc and init.larry.rc
          rm -rf init.rc init.larry.rc

          # Modify or create recovery.fstab for TWRP with generic partition names
          # NOTE: You'll need to update the partition paths once you build/test for your specific device.
          echo -e "# Default recovery.fstab, modify partition names based on your device's actual partitions\n/dev/block/by-name/system   /system      ext4    ro\n/dev/block/by-name/vendor   /vendor      ext4    ro\n/dev/block/by-name/cache    /cache       ext4    rw\n/dev/block/by-name/recovery /recovery    emmc    rw" > recovery.fstab

          # Modify Boardconfig.mk for recovery kernel
          echo "BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive" >> Boardconfig.mk
          echo "BOARD_RECOVERYIMAGE_PARTITION_SIZE := 2147483648" >> Boardconfig.mk

          # Check if lineage_larry.mk exists and modify it
          if [ -f lineage_larry.mk ]; then
            sed -i '/BOARD_KERNEL_CMDLINE/d' lineage_larry.mk
          fi

          # Other necessary TWRP specific changes (add recovery configurations, etc.)
          # Example: Set up kernel configs for TWRP if needed
          echo "CONFIG_RECOVERY=y" >> kernel_config

      - name: Push Modified Device Tree to GitHub
        run: |
          # Add the changes to git, commit and push them back to the repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Modify device tree for TWRP support"
          git push origin main
